import os
REDDIT_CLIENT_ID = os.environ.get('REDDIT_CLIENT_ID')
REDDIT_CLIENT_SECRET = os.environ.get('REDDIT_CLIENT_SECRET')
REDDIT_USER_AGENT = os.environ.get('REDDIT_USER_AGENT')
REDDIT_PASSWORD = os.environ.get('REDDIT_PASSWORD')
REDDIT_USERNAME = os.environ.get('REDDIT_USERNAME')